title: Morui
description: "Artist, developer, and Dota 2 captain"
baseurl: ""
url: "https://moruika.github.io"

current_status_en: "Creating a game."
current_status_ru: "Делаю игру."

markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

collections:
  posts:
    output: true

exclude:
  - README.md
